language: node_js
node_js:
  - "10.15.3"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
script:
  - yarn
  - yarn build
  - yarn build-prod
