os: linux
dist: bionic
language: node_js

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install --lts
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - ./tools/set_webos_cli.sh
cache:
  yarn: true
script:
  - yarn
  - yarn build
  - yarn build-ipk
